Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,33 +1,40 @@
-name: Sync Fork with Upstream
+name: Upstream Sync
+
+permissions:
+  contents: write
 
 on:
   schedule:
-    - cron: '1 10 * * *'  # 每天午夜运行同步（可以根据需要调整时间）
-  workflow_dispatch:  # 手动触发工作流
+    - cron: "0 0 * * *" # every day
+  workflow_dispatch:
 
 jobs:
-  sync:
+  sync_latest_from_upstream:
+    name: Sync latest commits from upstream repo
     runs-on: ubuntu-latest
+    if: ${{ github.event.repository.fork }}
 
     steps:
-    - name: Checkout Fork
-      uses: actions/checkout@v2
-      with:
-        ref: main  # 使用目标分支（如main或其他分支）
+      # Step 1: run a standard checkout action
+      - name: Checkout target repo
+        uses: actions/checkout@v3
 
-    - name: Set Up Git
-      run: |
-        git config --global user.name "GitHub Actions"
-        git config --global user.email "actions@github.com"
+      # Step 2: run the sync action
+      - name: Sync upstream changes
+        id: sync
+        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
+        with:
+          upstream_sync_repo:  vernesong/OpenClash
+          upstream_sync_branch: master
+          target_sync_branch: master
+          target_repo_token: ${{ secrets.GITHUB_TOKEN }} # automatically generated, no need to set
 
-    - name: Add Upstream Remote
-      run: git remote add upstream https://github.com/vernesong/OpenClash.git
+          # Set test_mode true to run tests instead of the true action!!
+          test_mode: false
 
-    - name: Fetch Upstream
-      run: git fetch upstream
-
-    - name: Merge Upstream into Fork
-      run: |
-        git checkout main  # 切换到你的目标分支
-        git merge upstream/main  --allow-unrelated-histories  # 强制合并不同历史的分支
-        git push origin main  # 将更改推送到你的 fork 仓库
+      - name: Sync check
+        if: failure()
+        run: |
+          echo "[Error] 由于上游仓库的 workflow 文件变更，导致 GitHub 自动暂停了本次自动更新，你需要手动 Sync Fork 一次，详细教程请查看项目README.md "
+          echo "[Error] Due to a change in the workflow file of the upstream repository, GitHub has automatically suspended the scheduled automatic update. You need to manually sync your fork. Please refer to the project README.md for instructions. "
+          exit 1
